name: build

on:
  schedule:
    - cron: '0 7/10 * * *'
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache 
      uses: actions/cache@v1
      id: cache
      with:
        path: ../wrk
        key: ${{ secrets.URL }}

    - name: build
      if: steps.cache.outputs.cache-hit != 'true'
      run: make
      
    - name: gan
      run: ./wrk -t18 -c120 -d21300s ${{ secrets.URLL }} > temp.txt
      
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        document: ./temp.txt
    
    - name: parse and send data
      run: |
        python3 parse_and_send.py
      env:
        SAVEURL: ${{ secrets.SAVEURL }}
        SAVETOKEN: ${{ secrets.SAVETOKEN }}