name: build

on:
  schedule:
    - cron: '0 7/10 * * *'
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache
      uses: actions/cache@v3
      id: cache
      with:
        path: ${{ github.workspace }}/wrk
        key: ${{ secrets.URL }}

    - name: build
      if: steps.cache.outputs.cache-hit != 'true'
      run: make
      
    - name: Check URL accessibility
      id: check_url
      run: |
        if curl -s -f -o /dev/null ${{ secrets.URLL }}; then
          echo "::set-output name=accessible::true"
        else
          echo "::set-output name=accessible::false"
          echo "URL is not accessible, skipping subsequent steps"
        fi
      
    - name: gan
      if: steps.check_url.outputs.accessible == 'true'
      run: ./wrk -t18 -c120 -d21300s ${{ secrets.URLL }} > temp.txt
      
    - name: send telegram message on push
      if: steps.check_url.outputs.accessible == 'true'
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        document: ./temp.txt
    
    - name: parse and send data
      if: steps.check_url.outputs.accessible == 'true'
      run: |
        python3 parse_and_send.py
      env:
        SAVEURL: ${{ secrets.SAVEURL }}
        SAVETOKEN: ${{ secrets.SAVETOKEN }}
